// service.go contains the gRPC service descriptor, handler registration, and
// client stub implementation for NickNode. Normally generated by protoc-gen-go-grpc,
// this is hand-written because protoc was not available. It uses a JSON codec
// instead of protobuf wire format.
//
// Regenerate from proto when tooling is available:
//   protoc --go_out=. --go-grpc_out=. proto/nick/v1/node.proto
package pb

import (
	"context"
	"encoding/json"

	"google.golang.org/grpc"
	"google.golang.org/grpc/encoding"
)

const serviceName = "nick.v1.NickNode"

// ---------------------------------------------------------------------------
// JSON codec — used instead of protobuf since types are plain Go structs.
// ---------------------------------------------------------------------------

const codecName = "json"

func init() {
	encoding.RegisterCodec(jsonCodec{})
}

type jsonCodec struct{}

func (jsonCodec) Marshal(v interface{}) ([]byte, error)   { return json.Marshal(v) }
func (jsonCodec) Unmarshal(data []byte, v interface{}) error { return json.Unmarshal(data, v) }
func (jsonCodec) Name() string                             { return codecName }

// ---------------------------------------------------------------------------
// Server registration
// ---------------------------------------------------------------------------

// RegisterNickNodeServer registers the NickNode service implementation with a gRPC server.
func RegisterNickNodeServer(s *grpc.Server, srv NickNodeServer) {
	s.RegisterService(&nickNodeServiceDesc, srv)
}

var nickNodeServiceDesc = grpc.ServiceDesc{
	ServiceName: serviceName,
	HandlerType: (*NickNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "Ping", Handler: pingHandler},
		{MethodName: "DeployStrategy", Handler: deployStrategyHandler},
		{MethodName: "ListStrategies", Handler: listStrategiesHandler},
		{MethodName: "StopStrategy", Handler: stopStrategyHandler},
		{MethodName: "SubmitBacktest", Handler: submitBacktestHandler},
		{MethodName: "GetBacktestResult", Handler: getBacktestResultHandler},
		{MethodName: "CreateAlert", Handler: createAlertHandler},
		{MethodName: "ListAlerts", Handler: listAlertsHandler},
		{MethodName: "GetStatus", Handler: getStatusHandler},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamPrices",
			Handler:       streamPricesHandler,
			ServerStreams:  true,
		},
	},
	Metadata: "proto/nick/v1/node.proto",
}

// Unary handlers

func pingHandler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NickNodeServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/" + serviceName + "/Ping"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NickNodeServer).Ping(ctx, req.(*PingRequest))
	})
}

func deployStrategyHandler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployStrategyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NickNodeServer).DeployStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/" + serviceName + "/DeployStrategy"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NickNodeServer).DeployStrategy(ctx, req.(*DeployStrategyRequest))
	})
}

func listStrategiesHandler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStrategiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NickNodeServer).ListStrategies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/" + serviceName + "/ListStrategies"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NickNodeServer).ListStrategies(ctx, req.(*ListStrategiesRequest))
	})
}

func stopStrategyHandler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopStrategyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NickNodeServer).StopStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/" + serviceName + "/StopStrategy"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NickNodeServer).StopStrategy(ctx, req.(*StopStrategyRequest))
	})
}

func submitBacktestHandler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitBacktestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NickNodeServer).SubmitBacktest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/" + serviceName + "/SubmitBacktest"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NickNodeServer).SubmitBacktest(ctx, req.(*SubmitBacktestRequest))
	})
}

func getBacktestResultHandler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBacktestResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NickNodeServer).GetBacktestResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/" + serviceName + "/GetBacktestResult"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NickNodeServer).GetBacktestResult(ctx, req.(*GetBacktestResultRequest))
	})
}

func createAlertHandler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NickNodeServer).CreateAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/" + serviceName + "/CreateAlert"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NickNodeServer).CreateAlert(ctx, req.(*CreateAlertRequest))
	})
}

func listAlertsHandler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAlertsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NickNodeServer).ListAlerts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/" + serviceName + "/ListAlerts"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NickNodeServer).ListAlerts(ctx, req.(*ListAlertsRequest))
	})
}

func getStatusHandler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NickNodeServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/" + serviceName + "/GetStatus"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NickNodeServer).GetStatus(ctx, req.(*GetStatusRequest))
	})
}

// Stream handler

type nickNodeStreamPricesServer struct {
	grpc.ServerStream
}

func (s *nickNodeStreamPricesServer) Send(tick *PriceTick) error {
	return s.ServerStream.SendMsg(tick)
}

func streamPricesHandler(srv interface{}, stream grpc.ServerStream) error {
	in := new(StreamPricesRequest)
	if err := stream.RecvMsg(in); err != nil {
		return err
	}
	return srv.(NickNodeServer).StreamPrices(in, &nickNodeStreamPricesServer{stream})
}

// ---------------------------------------------------------------------------
// Client stub
// ---------------------------------------------------------------------------

type nickNodeClient struct {
	cc grpc.ClientConnInterface
}

// NewNickNodeClient creates a client stub for the NickNode service.
func NewNickNodeClient(cc grpc.ClientConnInterface) NickNodeClient {
	return &nickNodeClient{cc: cc}
}

func (c *nickNodeClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/"+serviceName+"/Ping", in, out, opts...)
	return out, err
}

func (c *nickNodeClient) DeployStrategy(ctx context.Context, in *DeployStrategyRequest, opts ...grpc.CallOption) (*DeployStrategyResponse, error) {
	out := new(DeployStrategyResponse)
	err := c.cc.Invoke(ctx, "/"+serviceName+"/DeployStrategy", in, out, opts...)
	return out, err
}

func (c *nickNodeClient) ListStrategies(ctx context.Context, in *ListStrategiesRequest, opts ...grpc.CallOption) (*ListStrategiesResponse, error) {
	out := new(ListStrategiesResponse)
	err := c.cc.Invoke(ctx, "/"+serviceName+"/ListStrategies", in, out, opts...)
	return out, err
}

func (c *nickNodeClient) StopStrategy(ctx context.Context, in *StopStrategyRequest, opts ...grpc.CallOption) (*StopStrategyResponse, error) {
	out := new(StopStrategyResponse)
	err := c.cc.Invoke(ctx, "/"+serviceName+"/StopStrategy", in, out, opts...)
	return out, err
}

func (c *nickNodeClient) StreamPrices(ctx context.Context, in *StreamPricesRequest, opts ...grpc.CallOption) (NickNode_StreamPricesClient, error) {
	streamDesc := &grpc.StreamDesc{
		StreamName:   "StreamPrices",
		ServerStreams: true,
	}
	stream, err := c.cc.NewStream(ctx, streamDesc, "/"+serviceName+"/StreamPrices", opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := stream.CloseSend(); err != nil {
		return nil, err
	}
	return &nickNodeStreamPricesClient{stream}, nil
}

type nickNodeStreamPricesClient struct {
	grpc.ClientStream
}

func (s *nickNodeStreamPricesClient) Recv() (*PriceTick, error) {
	out := new(PriceTick)
	if err := s.ClientStream.RecvMsg(out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nickNodeClient) SubmitBacktest(ctx context.Context, in *SubmitBacktestRequest, opts ...grpc.CallOption) (*SubmitBacktestResponse, error) {
	out := new(SubmitBacktestResponse)
	err := c.cc.Invoke(ctx, "/"+serviceName+"/SubmitBacktest", in, out, opts...)
	return out, err
}

func (c *nickNodeClient) GetBacktestResult(ctx context.Context, in *GetBacktestResultRequest, opts ...grpc.CallOption) (*GetBacktestResultResponse, error) {
	out := new(GetBacktestResultResponse)
	err := c.cc.Invoke(ctx, "/"+serviceName+"/GetBacktestResult", in, out, opts...)
	return out, err
}

func (c *nickNodeClient) CreateAlert(ctx context.Context, in *CreateAlertRequest, opts ...grpc.CallOption) (*CreateAlertResponse, error) {
	out := new(CreateAlertResponse)
	err := c.cc.Invoke(ctx, "/"+serviceName+"/CreateAlert", in, out, opts...)
	return out, err
}

func (c *nickNodeClient) ListAlerts(ctx context.Context, in *ListAlertsRequest, opts ...grpc.CallOption) (*ListAlertsResponse, error) {
	out := new(ListAlertsResponse)
	err := c.cc.Invoke(ctx, "/"+serviceName+"/ListAlerts", in, out, opts...)
	return out, err
}

func (c *nickNodeClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, "/"+serviceName+"/GetStatus", in, out, opts...)
	return out, err
}
